In [1]:
import numpy as np
import pandas as pd

In [13]:
arr1=np.arange(1,11)
print(arr1)
reshape_arr1=arr1.reshape(2,5)
print('The reshaped array is \n:', reshape_arr1)

[ 1  2  3  4  5  6  7  8  9 10]
The reshaped array is 
: [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [21]:
arr2=np.arange(1,21)
print(arr2)
i_5=arr2[5]
i_15=arr2[15]
print('The 5th element in the array is: ',i_5)
print('The 15th element in the array is: ',i_15)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
The 5th element in the array is:  6
The 15th element in the array is:  16


In [31]:
series1=pd.Series({'Apples': 3, 'Bananas': 2, 'Oranges': 1})
print(series1)
series1['Pears']=4
print('The updated sereies is:\n ', series1)

Apples     3
Bananas    2
Oranges    1
dtype: int64
The updated sereies is:
  Apples     3
Bananas    2
Oranges    1
Pears      4
dtype: int64


In [63]:
mydata={'name': ['John', 'Anna', 'Akhil', 'Linda', 'Tom', 'Mary', 'Jack', 'Kate', 'Steve', 'Emma'],
        'age': np.random.randint(20, 45, 10),
        'gender': np.random.choice(['Male', 'Female'], 10)}
df1=pd.DataFrame(mydata)
print(df1)

    name  age  gender
0   John   29    Male
1   Anna   20    Male
2  Akhil   31  Female
3  Linda   36  Female
4    Tom   24  Female
5   Mary   40    Male
6   Jack   20  Female
7   Kate   20    Male
8  Steve   20  Female
9   Emma   43  Female


In [65]:
occupation = np.tile(['Programmer', 'Manager', 'Analyst'], len(df1) // 3 + 1)[:len(df1)]
df1['occupation'] = occupation
print(df1)

    name  age  gender  occupation
0   John   29    Male  Programmer
1   Anna   20    Male     Manager
2  Akhil   31  Female     Analyst
3  Linda   36  Female  Programmer
4    Tom   24  Female     Manager
5   Mary   40    Male     Analyst
6   Jack   20  Female  Programmer
7   Kate   20    Male     Manager
8  Steve   20  Female     Analyst
9   Emma   43  Female  Programmer


In [69]:
age_row=df1[df1['age']>=30]
print('The rows with age greater than or equal to 30 are: \n',age_row)

The rows with age greater than or equal to 30 are: 
     name  age  gender  occupation
2  Akhil   31  Female     Analyst
3  Linda   36  Female  Programmer
5   Mary   40    Male     Analyst
9   Emma   43  Female  Programmer


In [71]:
df_to_csv=df1.to_csv('EmployeeData.csv',index=False)
read_csv=pd.read_csv('EmployeeData.csv')
print(read_csv)

    name  age  gender  occupation
0   John   29    Male  Programmer
1   Anna   20    Male     Manager
2  Akhil   31  Female     Analyst
3  Linda   36  Female  Programmer
4    Tom   24  Female     Manager
5   Mary   40    Male     Analyst
6   Jack   20  Female  Programmer
7   Kate   20    Male     Manager
8  Steve   20  Female     Analyst
9   Emma   43  Female  Programmer
